### ISSUE TITLE
add some snippets

### ISSUE THREAD

**Issue by bshankar** [iAmMrinal0/yasnippet-purescript#1] opened 2018-02-27 03:14 UTC
The repository is currently unsuable as it contains no snippets whatsoever.

**Comment by iAmMrinal0** [comment] 2018-02-27 08:26
I am following the principle from [this](https://github.com/kelseyhightower/nocode) It's a feature, not a bug, thus closing.

**Closed by iAmMrinal0** 2018-02-27 08:26 UTC
